#PATH to all data
data_dir: PATH_TO_ALL_FILES

########## EXPORT DATA ##########

#Connecting to a database
adapter: mysql2
host: localhost
database: drupal
user:
password:

# DRUPAL

drupal_content_types_json: PATH_TO_FILE/drupal_content_types.json
drupal_boolean_columns: PATH_TO_FILE/boolean_columns.yml
drupal_base_url: http://example_hostname.com